#!/usr/bin/env zsh
#
# Zsh Configuration - Modular Loader
# All configuration is split into ~/.config/zsh/*.zsh files
#

# Source all config files in order
setopt NULL_GLOB
for config in ~/.config/zsh/*.zsh; do
    [[ -f "$config" ]] && source "$config"
done
setopt NO_NULL_GLOB

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/neo/.lmstudio/bin"
# End of LM Studio CLI section
