[[mgr.prepend_keymap]]
on  = "<D-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on   = "<C-t>"
run  = "plugin tv"
desc = "Jump to a file via television"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin tv dirs"
desc = "Jump to a directory via television"

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "plugin tv text"
desc = "Open files using neovim and jump to the match"

[[mgr.prepend_keymap]]
on  = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
desc = "Cycle through previewers"
on   = "p"
run  = "plugin mux --args=next"

[[mgr.prepend_keymap]]
desc = "Toggle media metadata"
on   = "<F9>"
run  = "plugin mediainfo --args=toggle-metadata"

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- ripdrag -x -i "$@"'
