-- ============================================================
-- settings.lua — Reads settings.toml and provides defaults
-- ============================================================
-- Do NOT edit this file for customization.
-- Edit settings.toml instead.
-- ============================================================

local wezterm = require('wezterm')
local platform = require('utils.platform')

-- Read and parse settings.toml using WezTerm's built-in TOML decoder
local settings_path = wezterm.config_dir .. '/settings.toml'
local f = io.open(settings_path, 'r')
local toml = {}
if f then
    local content = f:read('*a')
    f:close()
    toml = wezterm.serde.toml_decode(content) or {}
end

-- Helper: safe nested access
local function get(section, key)
    return toml[section] and toml[section][key] or nil
end

local settings = {}

-- ── Fonts ────────────────────────────────────────────────────
settings.font_family = get('fonts', 'family') or 'LiterationMono Nerd Font'
settings.font_weight = get('fonts', 'weight') or 'Medium'
settings.font_size = get('fonts', 'size') or (platform.is_mac and 12 or 9)

-- ── Appearance ───────────────────────────────────────────────
settings.max_fps = get('appearance', 'max_fps') or 120
settings.animation_fps = get('appearance', 'animation_fps') or 60
settings.background_opacity = get('appearance', 'background_opacity') or 0.96

-- ── General ──────────────────────────────────────────────────
settings.scrollback_lines = get('general', 'scrollback_lines') or 20000
settings.date_format = get('general', 'date_format') or '%a %H:%M:%S'

-- ── Shell / Launch ───────────────────────────────────────────
settings.default_shell = get('shell', 'default') -- nil = use platform defaults

-- ── Domains (WSL) ────────────────────────────────────────────
settings.wsl_user = get('wsl', 'user') or 'kevin'
settings.wsl_distro = get('wsl', 'distro') or 'Ubuntu'

-- ── Windows-specific paths ───────────────────────────────────
settings.win_user = get('windows', 'user') or 'kevin'

-- ── Backdrops ────────────────────────────────────────────────
settings.backdrop_images_dir = get('backdrops', 'images_dir')   -- nil = default dir
settings.backdrop_focus_color = get('backdrops', 'focus_color') -- nil = theme bg

return settings
