-- ============================================================
-- settings.lua — Reads config/*.toml (single source of truth)
-- ============================================================
-- Do NOT edit this file for customization.
-- Edit the TOML files in config/ instead:
--   config/fonts.toml       — Font family, size, fallback
--   config/appearance.toml  — Colors, window, cursor, backdrop
--   config/general.toml     — Shell, GPU, scrollback, behaviors
--   config/domains.toml     — SSH, WSL, platform, launch menu
--   config/keybindings.toml — AI layout, scroll amounts
--   config/plugins.toml     — Plugin enable/disable and options
--   config/theme.toml       — Status bar, tab title, file opener
--
-- This file contains NO default values. Every setting must be
-- defined in the TOML files.
-- ============================================================

local wezterm = require('wezterm')
local platform = require('utils.platform')

-- Read and parse all TOML files from config/ directory and merge into one table
-- NOTE: wezterm.glob() cannot be used here (yields across C-call boundary when
-- called from a require'd module). Use an explicit file list instead.
local config_dir = wezterm.config_dir .. '/config/'
local toml = {}

local config_files = {
   'appearance',
   'domains',
   'fonts',
   'general',
   'keybindings',
   'plugins',
   'theme',
}

for _, name in ipairs(config_files) do
   local path = config_dir .. name .. '.toml'
   local fh = io.open(path, 'r')
   if fh then
      local content = fh:read('*a')
      fh:close()
      local parsed = wezterm.serde.toml_decode(content)
      if parsed then
         for k, v in pairs(parsed) do
            if type(v) == 'table' and type(toml[k]) == 'table' then
               -- Merge sub-tables (e.g. two files both defining [plugins])
               for sk, sv in pairs(v) do
                  toml[k][sk] = sv
               end
            else
               toml[k] = v
            end
         end
      else
         wezterm.log_error('Failed to parse: ' .. path)
      end
   end
end

--- Safe nested access (no defaults — TOML is the source of truth).
--- get('section', 'key') — returns toml[section][key] or nil
--- get('section')         — returns toml[section] or nil
local function get(section, key)
   if key ~= nil then
      return toml[section] and toml[section][key]
   end
   return toml[section]
end

--- Convert empty strings to nil (TOML can't represent nil directly)
local function nil_if_empty(value)
   if value == '' then
      return nil
   end
   return value
end

local settings = {}

-- ── Fonts ────────────────────────────────────────────────────
settings.font_family = get('fonts', 'family')
settings.font_weight = get('fonts', 'weight')
settings.font_size = get('fonts', 'size')
settings.freetype_load_target = get('fonts', 'freetype_load_target')
settings.freetype_render_target = get('fonts', 'freetype_render_target')
settings.font_fallback = get('fonts', 'fallback')

-- ── Appearance ───────────────────────────────────────────────
settings.front_end = get('appearance', 'front_end')
settings.max_fps = get('appearance', 'max_fps')
settings.animation_fps = get('appearance', 'animation_fps')
settings.color_scheme = get('appearance', 'color_scheme')
settings.underline_thickness = get('appearance', 'underline_thickness')
settings.background_opacity = get('appearance', 'background_opacity')
settings.enable_scroll_bar = get('appearance', 'enable_scroll_bar')
settings.enable_tab_bar = get('appearance', 'enable_tab_bar')
settings.hide_tab_bar_if_only_one_tab = get('appearance', 'hide_tab_bar_if_only_one_tab')
settings.use_fancy_tab_bar = get('appearance', 'use_fancy_tab_bar')
settings.tab_max_width = get('appearance', 'tab_max_width')
settings.show_tab_index_in_tab_bar = get('appearance', 'show_tab_index_in_tab_bar')
settings.switch_to_last_active_tab_when_closing_tab =
   get('appearance', 'switch_to_last_active_tab_when_closing_tab')
settings.window_decorations = get('appearance', 'window_decorations')
settings.adjust_window_size_when_changing_font_size =
   get('appearance', 'adjust_window_size_when_changing_font_size')
settings.window_close_confirmation = get('appearance', 'window_close_confirmation')
settings.window_frame_active_titlebar_bg = get('appearance', 'window_frame_active_titlebar_bg')
settings.window_padding = get('appearance', 'window_padding')
settings.inactive_pane_hsb = get('appearance', 'inactive_pane_hsb')
settings.visual_bell = get('appearance', 'visual_bell')
settings.cursor = get('appearance', 'cursor')

-- Backdrop (uses nil_if_empty since TOML can't represent nil for optional strings)
settings.backdrop = get('appearance', 'backdrop') or {}
settings.backdrop.images_dir = nil_if_empty(settings.backdrop.images_dir)
settings.backdrop.focus_color = nil_if_empty(settings.backdrop.focus_color)
settings.backdrop.overlay_color = nil_if_empty(settings.backdrop.overlay_color)
settings.backdrop.overlay = settings.backdrop.overlay or {}

-- ── GPU / Rendering ──────────────────────────────────────────
settings.gpu = get('gpu') or {}

-- ── General ──────────────────────────────────────────────────
settings.automatically_reload_config = get('general', 'automatically_reload_config')
settings.exit_behavior = get('general', 'exit_behavior')
settings.exit_behavior_messaging = get('general', 'exit_behavior_messaging')
settings.status_update_interval = get('general', 'status_update_interval')
settings.scrollback_lines = get('general', 'scrollback_lines')
settings.date_format = get('general', 'date_format')
settings.default_cwd = get('general', 'default_cwd')

-- ── Shell / Launch ───────────────────────────────────────────
settings.default_shell = get('shell', 'default')
local shell_defaults = get('shell', 'default_prog') or {}
settings.default_prog = settings.default_shell
   or (platform.is_win and shell_defaults.windows)
   or (platform.is_linux and shell_defaults.linux)
   or (platform.is_mac and shell_defaults.mac)
settings.launch_menu = get('launch_menu') or {}

-- ── Domains ──────────────────────────────────────────────────
settings.domains = get('domains') or {}

-- ── Platform ─────────────────────────────────────────────────
-- Supports both [platform.wsl] and legacy [wsl] paths.
-- TODO: remove [wsl]/[windows] fallback after migration
local plat_wsl = get('platform', 'wsl') or get('wsl') or {}
local plat_win = get('platform', 'windows') or get('windows') or {}
settings.wsl_user = plat_wsl.user
settings.wsl_distro = plat_wsl.distro
settings.win_user = plat_win.user

-- ── AI Layout ────────────────────────────────────────────────
settings.ai_layout = get('ai_layout') or {}

-- ── Keybindings ──────────────────────────────────────────────
settings.keybindings = get('keybindings') or {}

-- ── Plugins ──────────────────────────────────────────────────
settings.plugins = get('plugins') or {}
-- tabline_theme cascades: explicit value → color_scheme → nil (let plugin decide)
settings.plugins.tabline_theme = settings.plugins.tabline_theme or settings.color_scheme

-- ── Status Bar ───────────────────────────────────────────────
settings.status_bar = get('status_bar') or {}

-- ── Tab Title ────────────────────────────────────────────────
settings.tab_title = get('tab_title') or {}

-- ── New Tab Button ───────────────────────────────────────────
settings.new_tab_button = get('new_tab_button') or {}
settings.new_tab_button.colors = settings.new_tab_button.colors or {}

-- ── File Opener ──────────────────────────────────────────────
settings.file_opener = get('file_opener') or {}

-- ── UI Strings ───────────────────────────────────────────────
settings.ui_strings = get('ui_strings') or {}

return settings
